#!/bin/bash

docker build -t ros2-test -f Dockerfile .

docker run -it --name ROS2-Test \
  --device /dev/ttyUSB0:/dev/ttyUSB0 \
  -v $(pwd)/../../:/workspaces/ROS2-SW \
  ros2-test

# docker run -it --name ROS2-Test \
#   --device /dev/ttyUSB0:/dev/ttyUSB0 \
#   -v $(pwd)/../../:/workspaces/ROS2-WS \
#   ros2-test

