#!/bin/bash

CONTAINER_DIRECTORY="Container"
ROS2_DIRECTORY="${CONTAINER_DIRECTORY}/ROS2"
ROS2_BASE_DIRECTORY="ROS2-Base"
SSH_SERVER_DIRECTORY="SSH_Server"

cd ${ROS2_DIRECTORY}
docker build --network=host -f Dockerfile -t ros2 .
cd ../${ROS2_BASE_DIRECTORY}
docker build --network=host -f Dockerfile -t ros2-base .
cd ../${SSH_SERVER_DIRECTORY}
docker build --network=host -f Dockerfile -t ssh-server .
cd ../../

docker compose up -d
docker compose logs -f ROS2 &


# echo "Waiting... "
# get_entrypoint_script_status() {
#     return $(docker exec "ROS2-Base" cat /tmp/entrypoint_done)
# }

# while ! get_entrypoint_script_status; do
#     sleep 5
#     echo "Still waiting... "
# done

# echo "Build complete... "
# sleep 1
# docker exec ROS2-Base bash -c 'rm /tmp/entrypoint_done'



# winpty docker exec -it ROS2 bash
