#!/bin/bash

if [ "$1" == "setup" ]; then
    sudo apt-get update
    sudo apt-get install -y hostapd dnsmasq

    sudo bash -c 'cat > /etc/hostapd/hostapd.conf << EOF
interface=wlan0
driver=nl80211
ssid=JetsonNanoAP
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=YourStrongPassword
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
EOF'

    sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig

    sudo bash -c 'cat > /etc/dnsmasq.conf << EOF
interface=wlan0
dhcp-range=192.168.50.2,192.168.50.20,255.255.255.0,24h
EOF'

    sudo bash -c 'cat >> /etc/network/interfaces << EOF
auto wlan0
iface wlan0 inet static
    address 192.168.50.1
    netmask 255.255.255.0
EOF'

    sudo systemctl unmask hostapd
    sudo systemctl enable hostapd
    sudo systemctl start hostapd
    sudo systemctl restart dnsmasq

elif [ "$1" == "revert" ]; then
    sudo systemctl stop hostapd
    sudo systemctl stop dnsmasq
    sudo systemctl disable hostapd
    sudo mv /etc/dnsmasq.conf.orig /etc/dnsmasq.conf
    sudo systemctl restart dnsmasq
fi
