#!/bin/bash

#echo $0 $1

#rosdep install -i --from-path src --rosdistro iron -y

# colcon build --packages-select test_pkg operations optics
colcon build
. install/setup.bash
#ros2 run test_pkg tester

