# Use an appropriate base image
FROM ubuntu:20.04

#install dependecies
RUN apt-get update && apt-get install -y \
    hostapd \
    dnsmasq \
    iproute2 \
    iptables \
    net-tools \
    wireless-tools


