name: Build and Push Docker Image with Kaniko

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Build with Kaniko
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: kaniko
          cache: true
          cache_registry: cache
      - name: Build Docker image with Kaniko
        run: |
          echo "<<<<Building Docker image with Kaniko>>>>>>>"
          pwd
          /kaniko/executor \
            --dockerfile /github/workspace/Dockerfile \
            --context dir:///github/workspace \
            --oci-layout-path /github/workspace/oci-layout
          echo "<<<<Building Docker image with Kaniko FINISHED>>>>>>>"

      - name: Save OCI layout as artifact
        uses: actions/upload-artifact@v2
        with:
          name: oci-layout
          path: ./oci-layout
